language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
    - server/node_modules
    - client/node_modules
script:
  - cd client && npm i && npm run test -- --coverage --watchAll=false && codecov && cd ../server && npm i && npm run test  -- --coverage --watchAll=false && codecov
ignore:
  - "./client/src/serviceWorker.js" 
