language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
    - server/node_modules
    - client/node_modules
script:
  - cd client && npm i && cd ../server && npm i && cd ../ npm run coverage
